<?php
$layout = $this->layout();
$navigation = $this->navigation();
?><!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <?php echo $this->headLink()->appendStylesheet('/css/admin.css') ?>
    <?php echo $this->headTitle() ?>
</head>
<body>
<header>
    <div class="navbar navbar-static" data-scrollspy="scrollspy">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="#">GraNat</a>
                <?php echo $navigation->menu($layout->navigation)->setUlClass('nav') ?>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#locale" class="dropdown-toggle" data-toggle="dropdown">Locale<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'locale', 'locale' => 'en')) ?>">EN</a></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'locale', 'locale' => 'ru')) ?>">RU</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <?php echo $this->flashMessages(); ?>
    <?php echo $navigation->breadcrumbs($layout->navigation)->setRenderInvisible(true); ?>
    <?php echo $layout->content ?>
</div>
<?php echo $this->headScript()
    ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js')
    ->appendFile('/js/bootstrap/js/bootstrap.js');
?>
</body>
</html>
