<?php
$this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8')
				 ->appendHttpEquiv('Content-Language', 'en-US');
?>
<?php echo $this->doctype();?>
<html>
<head>
	<?php echo $this->headMeta()?>
	<link rel="icon" type="image/png" href="/favicon.png" />
	<?php echo $this->headLink()->setStylesheet('/css/admin/login_admin.css')?>
	<?php echo $this->headTitle()?>
	<?php echo $this->headStyle()?>
</head>
<body>
	<?php echo $this->layout()->content?>
	<div id="footer-container">
		<div id="footer">&copy; Granat International <?php echo date('Y')?> | Website Design & Hosting by <a href="http://www.yobasoft.org.ua/">Yobasoft</a></div>
	</div>
	<?php echo $this->headScript()
			->setFile('http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js')
			->appendFile('/js/form/jquery.form.js')
			->appendFile('/js/scrollable/scrollable.min.js')
			->appendFile('/js/admin/login.js')
	?>
	
</body>
</html>