<h1 id="catalog-h1"><?php echo $this->translate('Наш каталог')?></h1>
<hr>
<?php if (count($this->models) > 0) { ?>
<div id="catalog">
    <a href="#prev" class="arrow prev"><span></span></a>

    <div class="oh images-container">
        <ul class="images" style="width: 2000%;"><?php
            foreach ($this->models as /** @var Model_Model $model */
            $model) {
            $imagePath = $this->imagePathHelper->direct($model);
            ?>
            <li><a title="<?php echo $model->name?>" href="<?php echo $this->url(array(
                                                                     'model_id' => $model->getId(),
                                                                     'model_name_hash' => $this->urlPartTranslit($model->name)
                                                                 ), 'model', true)?>"><em>&nbsp;</em><img
                src="/<?php echo $imagePath?>/<?php echo $model->getMainPhoto()->getFilename(Model_ModelPhoto::THUMBNAIL_ROLL)?>"
                alt="<?php echo $model->name?>" height="155" width="139"></a></li>
            <?php } ?></ul>
    </div>
    <a href="#next" class="arrow next"><span></span></a>
</div>
<?php } ?>
<h1 id="about-us-h1"><?php echo $this->translate('Несколько слов о нас')?></h1>
<hr>
<div id="aboutus-container" class="oh">
    <p>Студия моды &laquo;Гра Нат&raquo; была основана в 2006 году. Основным направлением является создание оригинальных
        дизайнерских нарядов. Коктейльные, вечерние платья, повседневная одежда, свадебные платья.</p>

    <p>В 2011 году был открыт второй салон-студия &laquo;GraNat&raquo;, в котором вы можете приобрести наряды нашей
        студии
        .</p>

    <div class="half vcard fl">
        <div class="profile-image big">
            <em>&nbsp;</em>
            <img src="/images/owner.jpg" alt="Наталья Гречаная" class="photo">
        </div>
        <p>Основатель и дизайнер одежды <span class="org">&laquo;GraNat&raquo;</span> <a href=""><span class="fn">Наталья Гречаная</span></a>
        </p>

        <p>Мы можем обсудить детали вашего заказа по телефону: <span class="tel">+380509288713</span></p>

        <p>Также вы можете отправить ваши пожелания или предложения электронным письмом по адресу: <a class="email"
                                                                                                      href="mailto:natali.grechanaya@gmail.com">natali.grechanaya@gmail.com</a>
        </p>
    </div>
    <div class="half vcard fl">
        <div class="profile-image big">
            <em>&nbsp;</em>
            <img src="/images/crap/image7.jpg" alt="Салон GraNat" class="photo">
        </div>
        <p>Наши наряды выполняются из итальянских тканей с использованием вышивки бисером и кристаллов Сваровски. Также
            можно приобрести ткани из Италии, Франции, ОАЭ.</p>

        <p>Наш адрес: <span class="adr"><span class="street-address">ул. Адмирала Макарова, 26, </span><span
            class="locality">Николаев</span>, <span class="country-name">Украина</span></span>. Телефон: <span
            class="tel">(0512) 47-88-51</span></p>

        <p><span class="adr"><span class="street-address">ул. Советская (ул. Большая Морская, 67/7),
        </span><span class="locality">Николаев</span>, <span class="country-name">Украина</span></span>. Телефон: <span
            class="tel">(0512) 37-00-99</span></p>
    </div>
</div>
<div id="shapes">
    <div class="shapes-container oh">
        <div id="models" class="shape">
            <h1 id="models-h1"><?php echo $this->translate('Наши модели')?></h1>
            <ul class="random"><?php foreach ($this->randomModels as /** @var Model_Model $model */
                $model) { ?>
                <li><a href="<?php echo $this->url(array(
                                               'model_id' => $model->getId(),
                                               'model_name_hash' => $this->urlPartTranslit($model->name)
                                           ), 'model', true)?>"><?php echo $model->name?></a></li><?php } ?>
            </ul>
        </div>
        <div id="materials" class="shape half">
            <h1 id="materials-h1"><?php echo $this->translate('Коллекция тканей')?></h1>
            <ul class="random"><?php foreach ($this->randomFabrics as /** @var Model_Fabric $fabric */
                $fabric) { ?>
                <li><a href="<?php echo $this->url(array(), 'fabrics', true)?>"><?php echo $fabric->name?></a></li><?php } ?>
            </ul>
        </div>
    </div>
    <p>К каждой вещи, применяя желание творить, фантазировать, можно найти свой подход, дать возможность радовать Вас и
        дальше! </p>
</div>
<div id="services">
    <h1><?php echo $this->translate('Услуги')?></h1>
    <hr>
    <p>Мы работаем на рынке сферы услуг четвертый год. Почти все мастера работают с момента основания ателье. Девиз
        нашего коллектива: «Выполнить хорошо свою работу мало – клиента нужно удивить!»</p>

    <div class="one-third fl">
        <div class="wrap">
            <div class="profile-image small">
                <em>&nbsp;</em>
                <img src="/images/crap/image8.jpg" alt="Визажист" class="photo" height="90" width="84">
            </div>
            <h2>Визажист</h2>

            <p>Доведите свой образ до совершенства с помощью наших профессиональных визажистов</p>
        </div>
    </div>
    <div class="one-third fl">
        <div class="wrap">
            <div class="profile-image small">
                <em>&nbsp;</em>
                <img src="/images/crap/image9.jpg" alt="Парикмахер" class="photo" height="90" width="84">
            </div>
            <h2>Парикмахер</h2>

            <p>Наши парикмахеры смогут сделать вам прическу любой сложности.</p>
        </div>
    </div>
    <div class="one-third fl">
        <div class="wrap">
            <div class="profile-image small">
                <em>&nbsp;</em>
                <img src="/images/crap/image10.jpg" alt="Стилист" class="photo" height="90" width="84">
            </div>
            <h2>Стилист</h2>

            <p>Создайте свой неповторимы стиль, а наши стилисты вам помогут в этом.</p>
        </div>
    </div>
</div>
<?php
    $this->headScript()
    ->appendFile('/js/jscrollpane/jquery.mousewheel.js')
    ->appendFile('/js/scrollable/scrollable.js')
    ->appendFile('/js/index.js');
$this->headTitle($this->translate('Главная'));
?>
