<? if ($this->pageCount > 1) {
	$routeParams = (array)$this->routeParams;
?>
<div class="center">
<ul class="oh inline center-container" id="paginator">
<? for ($i=$this->firstPageInRange;$i<=$this->lastPageInRange;$i++) { $routeParams['page'] = $i; ?>
	<li p="<?=$i?>"<?php if ($this->current == $i) echo ' class="active"' ?>>
		<a href="<?=$this->url($routeParams, 'collectionChain')?>" title="Page <?=$i?>"><?=$i?></a>
	</li>
<? } ?>
</ul>
</div>
<? } ?>