<div id="fabrics">
	<h1>Коллекция тканей</h1>
	<hr>
	<?php if (count($this->fabrics) > 0) { ?>
	<ul><?php foreach($this->fabrics as /** @var Model_Fabric $fabric */$fabric) { ?>
		<li>
			<div><em></em><img src="" alt="">

				<h2><?=$fabric->name?></h2>
				<p><?=$fabric->description?></p>
			</div>
		</li>
	<?php } ?></ul>
	<?php } ?>
	<?=$this->paginationControl($this->fabrics, null, null, array(
		'routeName' => 'allFabrics'
	))?>
</div>
<?php $this->headTitle('Ткани') ?>
