<ul class="toolbar">
	<li><a href="<?=$this->url(array('action' => 'add'))?>">Add model</a></li>
	<li><a href="#" onclick="$('#delete-models').submit();return false;">Delete Selected</a></li>
</ul>
<form id="delete-models" action="<?=$this->url(array('module'=>'admin','controller'=>'models','action'=>'delete-models'),null, true)?>" method="post">
<table>
	<tr>
		<th class="checkbox"><input type="checkbox" class="select-all" name="all" id="models-select-all" /></th>
		<th>Name</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<?php $i = 0; foreach ($this->models as $model) { ?>
	<tr<?=($i++ & 1)?' class="odd"':''?>>
		<td class="checkbox"><input type="checkbox" name="model[<?=$model->id?>]" id="model-<?=$model->id?>" value="<?=$model->id?>"></td>
		<td><?=$model->name?></td>
		<td><a href="<?=$this->url(array('action' => 'edit', 'id' => $model->id))?>">Edit</a></td>
		<td><a href="<?=$this->url(array('action' => 'delete', 'id' => $model->id))?>">Delete</a></td>
	</tr><?php } ?>
</table>
</form>
<?=$this->paginator?>
<?php $this->headTitle('Models')?>