<?php
if ($this->pageCount > 1) {
    $routeParams = (isset($this->routeParams)) ? $this->routeParams : array();
    $routeName = (isset($this->routeName)) ? $this->routeName : 'default';
    ?>
<div class="center">
    <ul class="oh inline center-container" id="paginator">
        <? for ($i = $this->firstPageInRange; $i <= $this->lastPageInRange; $i++) {
        $routeParams['page'] = $i;
        ?>
        <li p="<?php echo $i?>"<?php if ($this->current == $i) echo ' class="active"' ?>>
            <a href="<?php echo $this->url($routeParams, $routeName)?>"
               title="<?php echo $this->translate('Страница')?> <?php echo $i?>"><?php echo $i?></a>
        </li>
        <? } ?>
    </ul>
</div>
<? } ?>
