<?php if ($this->pageCount > 1) { ?>
<div class="center">
<ul class="oh inline center-container" id="paginator">
<?php if (isset($this->previous)) { ?>
	<li p="<?php echo $this->first?>" class="button first"><a href="<?php echo $this->url(array('page' => $this->first))?>"><small>«</small>First</a></li>
	<li class="spacer">...</li>
	<li p="<?php echo $this->previous?>" class="button prev"><a href="<?php echo $this->url(array('page' => $this->previous))?>"><small>‹</small>Prev</a></li>
<?php } ?>

<?php for ($i=$this->firstPageInRange;$i<=$this->lastPageInRange;$i++) { ?>
	<li p="<?php echo $i?>"<?php if ($this->current == $i) echo ' class="active"' ?>><a href="<?php echo $this->url(array('page' => $i))?>"><?php echo $i?></a></li>
<?php } ?>
<?php if (isset($this->next)) { ?>
	<li p="<?php echo $this->next?>" class="button next"><a href="<?php echo $this->url(array('page' => $this->next))?>">Next<small>›</small></a></li>
	<li class="spacer">...</li>
	<li p="<?php echo $this->last?>" class="button last"><a href="<?php echo $this->url(array('page' => $this->last))?>">Last<small>»</small></a></li>
<?php } ?>
</ul>
</div>
<?php } ?>