<?php $form = $this->element; ?>
<?php echo $form->id ?>
<?php echo $form->title->setAttrib('class', 'span7') ?>
<?php echo $form->description->setAttribs(array(
    'rows' => 10,
    'class' => 'span7'
)) ?>
<?php if ($this->element->id) { ?>
<div class="models">
    <div class="grey-h2">
        <h2 class="fl">Main (Title) model</h2>
    </div>
    <dl class="zend_form last">
        <dt id="modelTitle-label">&nbsp;</dt>
        <dd id="modelTitle-element">
            <table id="files" width="50%" align="center">
                <tr>
                    <td class="preview">
                        <ul><?php
                            $models = $this->element->mainModelId->getMultiOptions();
                            $mainModelId = $this->element->mainModelId->getValue();
                            if ($mainModelId == 0 && count($models) > 0) {
                                $mainModelId = reset(array_keys($models));
                            }
                            foreach ($models as $model_id => $model) {
                                ?>
                                <li>
                                    <label for="model-<?php echo $model_id?>">
                                        <div class="image">
                                            <em>&nbsp;</em>
                                            <img alt="<?php echo $model['title']?>"
                                                 src="/<?php echo $model['path']?>/<?php echo $model['thumb']?>">
                                        </div>
                                        <input class="checkable" <?php if ($model_id == $mainModelId) {
                                            echo ' checked="checked"';
                                        } ?> type="radio" name="mainModelId" id="model-<?php echo $model_id?>"
                                               value="<?php echo $model_id?>"/><?php echo $model['title']?></label>
                                </li>
                                <? } ?></ul>
                    </td>
                </tr>
            </table>
        </dd>
    </dl>
    <?php echo $this->element->id?>
</div>
<? } ?>
<div class="form-actions">
    <?php echo $this->formButton('submit', 'Save changes', array('type' => 'submit', 'class' => 'btn primary'))?>
</div>
<?php $this->headLink()
    ->appendStylesheet('/css/admin/jquery.fileupload-ui.css') ?>
