<div class="modal-header"><h3>GraNat</h3></div>
<div class="modal-body">
    <?php echo $this->element->email->setLabel('Email:')->setAttrib('class', 'span6') ?>
    <?php echo $this->element->password->setLabel('Password:')->setAttrib('class', 'span6') ?>
    <div class="clearfix">
        <div class="input">
            <ul class="inputs-list">
                <li>
                    <label><?php echo $this->element->remember ?>
                    <span>Remember</span></label>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="modal-footer">
    <input type="submit" class="btn primary" value="Login">
</div>
