<h1 class="login">Login</h1>
<dl>
	<dt><?php echo $this->element->email->getLabel()?></dt>
	<dd><?php echo $this->element->email?></dd>
</dl>
<dl>
	<dt><?php echo $this->element->password->getLabel()?></dt>
	<dd><?php echo $this->element->password?></dd>
</dl>
<div class="remember">
	<?php echo $this->element->is_remember?>
	<?php echo $this->formLabel('is_remember', $this->element->is_remember->getLabel())?>
</div>
<a class="forgot_password" href="#forgot-password">Forgot your password?</a>
<?php echo $this->element->referer?>
<?php echo $this->element->login?>