<?=$this->element->name?>
<?=$this->element->upload?>
<div class="file_upload_label">Upload files</div>
<?php $this->headScript()
	->appendFile('/js/admin/upload.js')
	->appendFile('/js/upload/jquery.fileupload.js')
	->appendFile('/js/upload/jquery.fileupload-ui.js') ?>

<?php
$this->headLink()
	->appendStylesheet('/css/admin/jquery.fileupload-ui.css')
?>
<script type="text/html" id="uploadRow">
	<tr>
		<td class="preview">
			{{ if (it.getAsDataURL) { }}<div class="image">
				<em>&nbsp;</em>
				<img src="{{=it.getAsDataURL()}}" alt="{{=it.name}}" width="84" height="90" />
			</div>{{ } }}
			<label>{{=it.name}}</label>
		</td>
		<td class="file_upload_progress" align="center"><div></div></td>
		<td class="file_upload_cancel">
			<button class="cancel ui-state-default ui-corner-all" title="Cancel">
				<span class="ui-icon ui-icon-cancel">Cancel</span>
			</button>
		</td>
	</tr>
</script>
<script type="text/html" id="progressRow">
	<tr>
		<td class="preview">
			<label for="coltitle_{{=it.id}}"><div class="image">
				<em>&nbsp;</em>
				<img src="/{{=it.path}}/{{=it.thumb}}" alt="{{=it.name}}">
			</div>
			<input type="radio" class="checkable" value="{{=it.id}}" name="modelTitle" id="coltitle_{{=it.id}}">Main Image</label>
		</td>
		<td class="file_upload_progress"><div></div></td>
		<td class="file_upload_delete">
			<button class="delete ui-state-default ui-corner-all" title="Delete" data-id="{{=it.id}}">
				<span class="ui-icon ui-icon-closethick">Delete</span>
			</button>
		</td>
	</tr>
</script>