<?=$this->doctype()?>
<html lang="ru-RU">
<head>
	<title>Granat</title>
	<meta http-equiv="Content-Encoding" charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="/css/style.css" media="all"/>
	<!--[if IE]>
	<style type="text/css">
		hr {filter:alpha(opacity=43);}
	</style>
	<![endif]-->
	<!--[if lt IE 8]>
	<style type="text/css">
	
	</style>
	<![endif]-->
	<!--[if lt IE 7]>
	<style type="text/css">
	
	</style>
	<![endif]-->
</head>
<?php
$navigation = $this->getHelper('Navigation_Menu');
?>
<body>
	<div id="bodywrapper">
		<div id="logo"><a href="/">GraNat Natali Grechanaya</a></div>
		<div id="bodycontainer">
			<div id="header">
				<?=$navigation->renderMenu()?>
			</div>
			<div id="body">
				<div id="content"><?php echo $this->layout()->content; ?></div>
			</div>
			<div id="footer-spacer">&nbsp;</div>
		</div>
		<div id="footer">
			<div id="footer-wrapper">
				<div class="fl"><?=$navigation->renderMenu()?></div>
				<span id="copyright" class="fr">© 2011. GraNat.  Все права защищены</span>
			</div>
		</div>
	</div>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
	<script type="text/javascript" src="/js/js.js"></script>
</body>
</html>