<?=$this->doctype()?>
<html lang="ru-RU">
<head>
	<title>Granat</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="/css/reset.css" media="all"/>
	<link rel="stylesheet" type="text/css" href="/css/style.css" media="all"/>
	<!--[if IE]>
	<style type="text/css">
		hr {filter:alpha(opacity=43);}
	</style>
	<![endif]-->
	<!--[if lt IE 8]>
	<style type="text/css">
	
	</style>
	<![endif]-->
	<!--[if lt IE 7]>
	<style type="text/css">
	
	</style>
	<![endif]-->
</head>
<body>
	<div id="bodywrapper">
		<div id="logo">GraNat by Natali Grechanaya</div>
		<div id="bodycontainer">
			<div id="header">
				<ul class="menu">
					<li class="active"><a href="">Студия</a></li>
					<li><a href="">Галерея</a></li>
					<li><a href="">Ткани</a></li>
					<li><a href="">Контакты</a></li>
				</ul>
			</div>
			<div id="body">
				<div id="content" style="width:950px;"><?php echo $this->layout()->content; ?></div>
			</div>
			<div id="footer-spacer">&nbsp;</div>
		</div>
		<div id="footer">
			<div id="footer-wrapper">
				<ul class="menu fl">
					<li><a href="">Студия</a></li>
					<li><a href="">Галерея</a></li>
					<li><a href="">Ткани</a></li>
					<li class="last"><a href="">Контакты</a></li>
				</ul>
				<span id="copyright" class="fr">© 2011. GraNat.  Все права защищены</span>
			</div>
		</div>
	</div>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
	<script type="text/javascript" src="/js/js.js"></script>
</body>
</html>