<ul class="toolbar">
    <li><a href="<?=$this->url(array('action' => 'add'))?>">Add fabric</a></li>
    <li><a href="#" onclick="$('#delete-fabrics').submit();return false;">Delete Selected</a></li>
</ul>
<form id="delete-fabrics"
      action="<?=$this->url(array('module' => 'admin', 'controller' => 'fabrics', 'action' => 'delete'), null, true)?>"
      method="post">
    <table>
        <tr>
            <th class="checkbox"><input type="checkbox" class="select-all" name="all" id="fabrics-select-all"/></th>
            <th><?=$this->orderLink('Name', 'name')?></th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php $i = 0; foreach ($this->fabrics as $fabric) { ?>
        <tr<?=($i++ & 1) ? ' class="odd"' : ''?>>
            <td class="checkbox"><input type="checkbox" name="fabric[<?=$fabric->id?>]" id="fabric-<?=$fabric->id?>"
                                        value="<?=$fabric->id?>"></td>
            <td><label for="fabric-<?=$fabric->id?>"><?=$fabric->name?></label></td>
            <td><a href="<?=$this->url(array('action' => 'edit', 'id' => $fabric->id))?>">Edit</a></td>
            <td><a href="<?=$this->url(array('action' => 'delete', 'id' => $fabric->id))?>">Delete</a></td>
        </tr><?php } ?>
    </table>
</form>
<?= $this->paginator ?>
<?php $this->headTitle('Fabrics') ?>
