<ul class="toolbar">
    <li><a href="<?php echo $this->url(array('action' => 'add'))?>">Add fabric</a></li>
    <li><a href="#" onclick="$('#delete-fabrics').submit();return false;">Delete Selected</a></li>
</ul>
<form id="delete-fabrics"
      action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'fabrics', 'action' => 'delete'), null, true)?>"
      method="post">
    <table>
        <tr>
            <th class="checkbox"><input type="checkbox" class="select-all" name="all" id="fabrics-select-all"/></th>
            <th><?php echo $this->orderLink('Name', 'name')?></th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php $i = 0; foreach ($this->fabrics as $fabric) { ?>
        <tr<?php echo ($i++ & 1) ? ' class="odd"' : ''?>>
            <td class="checkbox"><input type="checkbox" name="fabric[<?php echo $fabric->getId()?>]" id="fabric-<?php echo $fabric->getId()?>"
                                        value="<?php echo $fabric->getId()?>"></td>
            <td><label for="fabric-<?php echo $fabric->getId()?>"><?php echo $fabric->name?></label></td>
            <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $fabric->getId()))?>">Edit</a></td>
            <td><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $fabric->getId()))?>">Delete</a></td>
        </tr><?php } ?>
    </table>
</form>
<?php echo  $this->paginator ?>
<?php $this->headTitle('Fabrics') ?>
