<div id="sidebar" class="shape">
	<h1>Наши коллекции</h1>
	<ul>
		<li><a href="#ketty">Ketty Perry</a></li>
		<li><a href="#trololo">Ololo Trololo</a></li>
		<li class="active"><a href="#helen">Helen Banks</a></li>
		<li><a href="#babka">Babka Paraska</a></li>
		<li><a href="#roland">Roland Emmelrich</a></li>
		<li><a href="#kelvin">Kelvin Klein</a></li>
	</ul>
</div>
<div id="collection" class="left-sidebar-body">
	<h1>Roland Emellrich</h1>
	<hr>
	<ul class="models">
		<li class="one">
			<div class="image"><em>&nbsp;</em><a href="#roland"><img src="/images/crap/collection_model_1.jpg" alt="Roland Emelrich"><span>Roland Emelrich</span></a></div>
		</li>
		<li class="two">
			<div class="image"><em>&nbsp;</em><a href="#roland"><img src="/images/crap/collection_model_1.jpg" alt="Roland Emelrich"><span>Roland Emelrich</span></a></div>
		</li>
		<li class="three">
			<div class="image"><em>&nbsp;</em><a href="#roland"><img src="/images/crap/collection_model_1.jpg" alt="Roland Emelrich"><span>Roland Emelrich</span></a></div>
		</li>
	</ul>
	<ul class="models">
		<li class="one">
			<div class="image"><em>&nbsp;</em><a href="#roland"><img src="/images/crap/collection_model_1.jpg" alt="Roland Emelrich"><span>Roland Emelrich</span></a></div>
		</li>
		<li class="two">
			<div class="image"><em>&nbsp;</em><a href="#roland"><img src="/images/crap/collection_model_1.jpg" alt="Roland Emelrich"><span>Roland Emelrich</span></a></div>
		</li>
	</ul>
</div>