<ul class="collections">
	<li class="one">
		<div class="image"><em>&nbsp;</em><a href="#roland"><img src="/images/crap/collection_1.jpg" alt="Roland Mouret"></a></div>
		<h1><a href="#roland">Roland Mouret</a></h1>
		<ul class="categories">
			<li><a href="#cat1">Прямой силуэт</a></li>
			<li><a href="#cat1">Силуэт русалка</a></li>
			<li><a href="#cat1">Пышные платья</a></li>
			<li><a href="#cat1">А-образный силуэт</a></li>
			<li><a href="#cat1">Стиль ампир</a></li>
			<li><a href="#cat1">Большие размеры</a></li>
		</ul>
	</li>
	<li class="two">
		<div class="image"><em>&nbsp;</em><a href="#ketty"><img src="/images/crap/collection_2.jpg" alt="Ketty Taylor"></a></div>
		<h1><a href="#ketty">Ketty Taylor</a></h1>
		<ul class="categories">
			<li><a href="#cat1">Прямой силуэт</a></li>
			<li><a href="#cat1">Силуэт русалка</a></li>
			<li><a href="#cat1">Пышные платья</a></li>
			<li><a href="#cat1">А-образный силуэт</a></li>
			<li><a href="#cat1">Стиль ампир</a></li>
			<li><a href="#cat1">Большие размеры</a></li>
		</ul>
	</li>
	<li class="three">
		<div class="image"><em>&nbsp;</em><a href="#helen"><img src="/images/crap/collection_3.jpg" alt="Helen Bump"></a></div>
		<h1><a href="#helen">Helen Bump</a></h1>
		<ul class="categories">
			<li><a href="#cat1">Прямой силуэт</a></li>
			<li><a href="#cat1">Силуэт русалка</a></li>
			<li><a href="#cat1">Пышные платья</a></li>
			<li><a href="#cat1">А-образный силуэт</a></li>
			<li><a href="#cat1">Стиль ампир</a></li>
			<li><a href="#cat1">Большие размеры</a></li>
		</ul>
	</li>
</ul>
<ul class="collections">
	<li class="one">
		<div class="image"><em>&nbsp;</em><a href="#ololo"><img src="/images/crap/collection_4.jpg" alt="Ololo Trololo"></a></div>
		<h1><a href="#ololo">Ololo Trololo</a></h1>
		<ul class="categories">
			<li><a href="#cat1">Прямой силуэт</a></li>
			<li><a href="#cat1">Силуэт русалка</a></li>
			<li><a href="#cat1">Пышные платья</a></li>
			<li><a href="#cat1">А-образный силуэт</a></li>
			<li><a href="#cat1">Стиль ампир</a></li>
			<li><a href="#cat1">Большие размеры</a></li>
		</ul>
	</li>
	<li class="two">
		<div class="image"><em>&nbsp;</em><a href="#babka"><img src="/images/crap/collection_5.jpg" alt="Babka Paraska"></a></div>
		<h1><a href="#babka">Babka Paraska</a></h1>
		<ul class="categories">
			<li><a href="#cat1">Прямой силуэт</a></li>
			<li><a href="#cat1">Силуэт русалка</a></li>
			<li><a href="#cat1">Пышные платья</a></li>
			<li><a href="#cat1">А-образный силуэт</a></li>
			<li><a href="#cat1">Стиль ампир</a></li>
			<li><a href="#cat1">Большие размеры</a></li>
		</ul>
	</li>
	<li class="three">
		<div class="image"><em>&nbsp;</em><a href="#vitton"><img src="/images/crap/collection_6.jpg" alt="Louis Vitton"></a></div>
		<h1><a href="#vitton">Louis Vitton</a></h1>
		<ul class="categories">
			<li><a href="#cat1">Прямой силуэт</a></li>
			<li><a href="#cat1">Силуэт русалка</a></li>
			<li><a href="#cat1">Пышные платья</a></li>
			<li><a href="#cat1">А-образный силуэт</a></li>
			<li><a href="#cat1">Стиль ампир</a></li>
			<li><a href="#cat1">Большие размеры</a></li>
		</ul>
	</li>
</ul>