<?php
$i = 0;
$classes = array('one', 'two', 'three');
?>
<ul class="collections"><?php foreach($this->collections as /** @var Model_Collection $collection */$collection) { ?>
	<?php $categories = $collection->getCategories(); ?>
	<li>
		<div class="<?=$classes[$i++ % 3]?>">
			<div class="image"><em>&nbsp;</em><a href="#roland"><img src="/images/crap/collection_1.jpg" alt="<?=$collection->name?>"></a></div>
			<h1><a href="#roland"><?=$collection->name?></a></h1>
			<?php if (count($categories) > 1) { ?><ul class="categories">
			<?php foreach($categories as /** @var Model_Category $category */$category) { ?>
				<li><a href="#cat1"><?=$category->name?></a></li>
			<?php } ?>
			</ul><?php } ?>
		</div>
	</li>
<?php } ?>
</ul>