<div class="login modal hide fade">
    <?php echo $this->form ?>
</div>
<noscript>
<div class="container" style="margin-top: -33px; position: absolute; top: 50%;">
    <div class="alert-message block-message error">
        <p><strong>Warning!</strong> You should turn on the javascript to log in.</p>
    </div>
</div>
</noscript>
<?php $this->headScript()->appendFile('/js/bootstrap/js/bootstrap-modal.js') ?>
<?php $this->headScript()->captureStart() ?>
$(function() {
$('.modal').modal({show: true});
})
<?php $this->headScript()->captureEnd() ?>
<?php $this->headTitle('GraNat admin') ?>
