<ul class="toolbar">
	<li><a href="<?=$this->url(array('action' => 'add'))?>">Add category</a></li>
	<li><a href="#" onclick="$('#delete-categories').submit();return false;">Delete Selected</a></li>
</ul>
<form id="delete-categories" action="<?=$this->url(array('module'=>'admin','controller'=>'categories','action'=>'delete-categories'),null, true)?>" method="post">
<table>
	<tr>
		<th class="checkbox"><input type="checkbox" class="select-all" name="all" id="categories-select-all" /></th>
		<th>Name</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<?php $i = 0; foreach ($this->categories as $category) { ?>
	<tr<?=($i++ & 1)?' class="odd"':''?>>
		<td class="checkbox"><input type="checkbox" name="category[<?=$category->id?>]" id="category-<?=$category->id?>" value="<?=$category->id?>"></td>
		<td><?=$category->name?></td>
		<td><a href="<?=$this->url(array('action' => 'edit', 'id' => $category->id))?>">Edit</a></td>
		<td><a href="<?=$this->url(array('action' => 'delete', 'id' => $category->id))?>">Delete</a></td>
	</tr><?php } ?>
</table>
</form>
<?=$this->paginator?>
<?php $this->headTitle('Categories')?>