<ul class="toolbar">
    <li><a href="<?php echo $this->url(array('action' => 'add'))?>">Add category</a></li>
    <li><a href="#" onclick="$('#delete-categories').submit();return false;">Delete Selected</a></li>
</ul>
<form id="delete-categories"
      action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'categories', 'action' => 'delete'), null, true)?>"
      method="post">
    <table>
        <tr>
            <th class="checkbox"><input type="checkbox" class="select-all" name="all" id="categories-select-all"/></th>
            <th>Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php $i = 0; foreach ($this->categories as /** @var \Entities\Category $category */ $category) { ?>
        <tr<?php echo ($i++ & 1) ? ' class="odd"' : ''?>>
            <td class="checkbox"><input type="checkbox" name="category[<?php echo $category->getId()?>]"
                                        id="category-<?php echo $category->getId()?>" value="<?php echo $category->getId()?>"></td>
            <td><label for="category-<?php echo $category->getId()?>"><?php echo $category->getTitle()?></label></td>
            <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $category->getId()))?>">Edit</a></td>
            <td><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $category->getId()))?>">Delete</a></td>
        </tr><?php } ?>
    </table>
</form>
<?php echo  $this->paginator ?>
<?php $this->headTitle('Categories') ?>
