<?php $this->headTitle('categories') ?>
<div class="row toolbar">
    <a href="<?php echo $this->url(array(
        'action' => 'add',
        'controller' => 'categories'
    ), 'admin-default')?>" class="btn primary pull-left">Add category</a>
    <a href="#delete"
       class="btn pull-right delete-selected"><i class="icon trash"></i>&nbsp;Delete Selected</a>
</div>
<form id="delete-categories"
      action="<?php echo $this->url(array(
          'controller' => 'categories',
          'action' => 'delete'), null, true)?>"
      method="post">
    <table class="table">
        <thead>
        <tr>
            <th class="checkbox span1"><input type="checkbox" class="select-all" name="all" id="categories-select-all"/></th>
            <th>Name</th>
            <th class="span1">Edit</th>
            <th class="span1">Delete</th>
        </tr>
        </thead>
        <tbody>
        <?php $i = 0; foreach ($this->categories as /** @var \Entities\Category $category */$category) { ?>
        <tr<?php echo ($i++ & 1) ? ' class="odd"' : ''?>>
            <td class="checkbox"><input type="checkbox" name="id[<?php echo $category->getId()?>]"
                                        id="category-<?php echo $category->getId()?>"
                                        value="<?php echo $category->getId()?>"></td>
            <td><label for="category-<?php echo $category->getId()?>"><?php echo $category->getTitle()?></label></td>
            <td><a class="btn info" href="<?php echo $this->url(array(
                'controller' => 'categories',
                'action' => 'edit',
                'id' => $category->getId()
            ), 'admin-editDelete')?>"><i class="icon white pencil"></i></a></td>
            <td><a class="btn danger" href="<?php echo $this->url(array(
                'controller' => 'categories',
                'action' => 'delete',
                'id' => $category->getId()
            ), 'admin-editDelete')?>"><i class="icon white trash"></i></a></td>
        </tr><?php } ?>
        </tbody>
    </table>
</form>
<?php echo  $this->categories ?>
