<ul class="toolbar">
	<li><a href="<?=$this->url(array('action' => 'add'))?>">Add brand</a></li>
	<li><a href="#" onclick="$('#delete-brands').submit();return false;">Delete Selected</a></li>
</ul>
<form id="delete-brands" action="<?=$this->url(array('module'=>'admin','controller'=>'brands','action'=>'delete-brands'),null, true)?>" method="post">
<table>
	<tr>
		<th class="checkbox"><input type="checkbox" class="select-all" name="all" id="brands-select-all" /></th>
		<th>Name</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<?php $i = 0; foreach ($this->brands as $brand) { ?>
	<tr<?=($i++ & 1)?' class="odd"':''?>>
		<td class="checkbox"><input type="checkbox" name="brand[<?=$brand->id?>]" id="brand-<?=$brand->id?>" value="<?=$brand->id?>"></td>
		<td><?=$brand->name?></td>
		<td><a href="<?=$this->url(array('action' => 'edit', 'id' => $brand->id))?>">Edit</a></td>
		<td><a href="<?=$this->url(array('action' => 'delete', 'id' => $brand->id))?>">Delete</a></td>
	</tr><?php } ?>
</table>
</form>
<?=$this->paginator?>
<?php $this->headTitle('Brands')?>