<?php $this->headTitle('Collections') ?>
<div class="row toolbar">
    <a href="<?php echo $this->url(array('action' => 'add', 'controller' => 'collections'), 'admin-default')?>" class="btn primary pull-left">Add collection</a>
    <a href="#delete"
       class="btn pull-right delete-selected"><i class="icon trash"></i>&nbsp;Delete Selected</a>
</div>
<form id="delete-collections"
      action="<?php echo $this->url(array(
          'controller' => 'collections',
          'action' => 'delete'), null, true)?>"
      method="post">
    <table class="table">
        <thead>
        <tr>
            <th class="checkbox span1"><input type="checkbox" class="select-all" name="all" id="collections-select-all"/></th>
            <th>Name</th>
            <th class="span1">Edit</th>
            <th class="span1">Delete</th>
        </tr>
        </thead>
        <tbody>
        <?php $i = 0; foreach ($this->collections as /** @var \Entities\Collection $collection */$collection) { ?>
        <tr<?php echo ($i++ & 1) ? ' class="odd"' : ''?>>
            <td class="checkbox"><input type="checkbox" name="id[<?php echo $collection->getId()?>]"
                                        id="collection-<?php echo $collection->getId()?>"
                                        value="<?php echo $collection->getId()?>"></td>
            <td><label for="collection-<?php echo $collection->getId()?>"><?php echo $collection->getTitle()?></label></td>
            <td><a class="btn info" href="<?php echo $this->url(array(
                'controller' => 'collections',
                'action' => 'edit',
                'id' => $collection->getId()
            ), 'admin-editDelete')?>"><i class="icon white pencil"></i></a></td>
            <td><a class="btn danger" href="<?php echo $this->url(array(
                'controller' => 'collections',
                'action' => 'delete',
                'id' => $collection->getId()
            ), 'admin-editDelete')?>"><i class="icon white trash"></i></a></td>
        </tr><?php } ?>
        </tbody>
    </table>
</form>
<?php echo  $this->collections ?>
