<ul class="toolbar">
	<li><a href="<?php echo $this->url(array('action' => 'add'))?>">Add collection</a></li>
	<li><a href="#" onclick="$('#delete-collections').submit();return false;">Delete Selected</a></li>
</ul>
<form id="delete-collections" action="<?php echo $this->url(array('module'=>'admin','controller'=>'collections','action'=>'delete-collections'),null, true)?>" method="post">
<table>
	<tr>
		<th class="checkbox"><input type="checkbox" class="select-all" name="all" id="collections-select-all" /></th>
		<th>Name</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<?php $i = 0; foreach ($this->collections as $collection) { ?>
	<tr<?php echo ($i++ & 1)?' class="odd"':''?>>
		<td class="checkbox"><input type="checkbox" name="collection[<?php echo $collection->id?>]" id="collection-<?php echo $collection->id?>" value="<?php echo $collection->id?>"></td>
		<td><label for="collection-<?php echo $collection->id?>"><?php echo $collection->name?></label></td>
		<td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $collection->id))?>">Edit</a></td>
		<td><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $collection->id))?>">Delete</a></td>
	</tr><?php } ?>
</table>
</form>
<?php echo $this->paginator?>
<?php $this->headTitle('Collections')?>