<?php
$i = 0;
$classes = array('one', 'two', 'three');
?><div id="sidebar" class="shape">
	<h1>Наши коллекции</h1>
	<ul><?php foreach($this->collections as /** @var Model_Collection $collection */$collection) { ?>
		<li><a href="<?=$this->url(array(
		                                'collection_id' => $collection->id,
			                            2 => $this->urlPartTranslit($collection->name)
		                           ), 'collection', true)?>"><?=$collection->name?></a></li>
	<?php } ?></ul>
</div>
<div id="collection" class="left-sidebar-body">
	<?php if (!$this->collection->isEmpty()) { ?><h1><?=$this->collection->name?></h1>
	<hr><?php } ?>
	<ul class="models"><?php foreach($this->models as /** @var Model_Model $model */$model) {
		$mainModelPhotoUrl = 'images/empty/big.jpg';
		$mainModelPhoto = $model->getMainPhoto();
		if (!$mainModelPhoto->isEmpty()) {
			$mainModelPhotoUrl = $this->imagePathHelper->direct($model)
								 . '/'
			                     . $mainModelPhoto->getFilename(Model_Photo::SIZE_BIG);
		}
	?>
		<li>
			<div class="<?=$classes[$i++ % 3]?>">
				<div class="image">
					<em>&nbsp;</em>
					<a href="<?=$url=$this->url(array(
								'model_id' => $model->id,
								2 => $this->urlPartTranslit($model->name)
						   ), 'model', true)?>">
						<img src="/<?=$mainModelPhotoUrl?>" alt="<?=$model->name?>">
					</a>
				</div>
				<a href="<?=$url?>"><span><?=$model->name?></span></a>
			</div>
		</li>
		<?php if ($i % 3 == 0) { ?><li class="clear"></li><?php } ?>
	<?php } ?></ul>
	<?php
		$paginationPartial = 'pagination/models.phtml';
		$routeParams = array(
			'collection_id' => $this->collection->id,
			'collection_name_hash' => $this->urlPartTranslit($this->collection->name)
		);
		if ($this->category && !$this->category->isEmpty()) {
			$paginationPartial = 'pagination/models-category.phtml';
			$routeParams['category_id'] = $this->category->id;
			$routeParams['category_name_hash'] = $this->urlPartTranslit($this->category->name);
		}
	?>
	<?=$this->paginationControl($this->models, null, $paginationPartial, array(
		'route' => $routeName,
		'routeParams' => $routeParams
	))?>
</div>