<?php
$i = 0;
$classes = array('one', 'two', 'three');
?>
<?php echo  $this->partial('models/_left-column.phtml', array('collections' => $this->collections)) ?>
<div id="collection" class="left-sidebar-body">
    <?php if (!$this->collection->isEmpty()) { ?><h1><?php echo $this->collection->name?></h1>
	<hr><?php } ?>
    <ul class="models"><?php foreach ($this->models as /** @var Model_Model $model */
                                      $model) {
        $mainModelPhotoUrl = 'images/empty/big.jpg';
        $mainModelPhoto = $model->getMainPhoto();
        if ($mainModelPhoto) {
            $mainModelPhotoUrl = $this->imagePathHelper->direct($model)
                . '/'
                . $mainModelPhoto->getFilename(\Entities\Model\Photo::THUMBNAIL_BIG);
        }
        ?>
        <li>
            <div class="<?php echo $classes[$i++ % 3]?>">
                <div class="image">
                    <em>&nbsp;</em>
                    <a href="<?php echo $url = $this->url(array(
                        'model_id' => $model->getId(),
                        'model_name_hash' => $this->urlPartTranslit($model->name)
                    ), 'model', true)?>">
                        <img src="/<?php echo $mainModelPhotoUrl?>" alt="<?php echo $model->name?>">
                    </a>
                </div>
                <a href="<?php echo $url?>"><span><?php echo $model->name?></span></a>
            </div>
        </li>
        <?php if ($i % 3 == 0) { ?><li class="clear"></li><?php } ?>
        <?php } ?></ul>
    <?php
    $routeName = 'allModels';
    $routeParams = array();
    if ($this->collection && !$this->collection->isEmpty()) {
        $this->headTitle('Коллекция «' . $this->collection->name . '» - ');

        $routeName = 'collectionChain';
        $routeParams = array(
            'collection_id' => $this->collection->getId(),
            'collection_name_hash' => $this->urlPartTranslit($this->collection->name)
        );
        if ($this->category && !$this->category->isEmpty()) {
            $routeParams['category_id'] = $this->category->getId();
            $routeParams['category_name_hash'] = $this->urlPartTranslit($this->category->name);
            $routeName = 'categorizedCollectionChain';
        }
    }
    ?>
    <?php echo $this->paginationControl($this->models, null, null, array(
    'routeParams' => $routeParams,
    'routeName' => $routeName
))?>
</div>
<?php $this->headTitle($this->translate('Модели')) ?>
