<?php
$i = 0;
$classes = array('one', 'two', 'three');
/** @var Model_Model $model */
$model = $this->model;
$mainModelPhotoUrl = 'images/empty/big.jpg';
$mainModelPhoto = $model->getMainPhoto();
$mainModelPhotoPath  = $this->imagePathHelper->direct($model);
if (!$mainModelPhoto->isEmpty()) {
	$mainModelPhotoUrl = $mainModelPhotoPath
						 . '/'
						 . $mainModelPhoto->getFilename(Model_ModelPhoto::SIZE_BIG);
}
$photos = $model->getPhotos();
$collection = $model->getCollection();

$next = $model->getNextModel();
$prev = $model->getPreviousModel();
?>
<?=$this->partial('models/_left-column.phtml', array('collections' => $this->collections))?>
<div id="model" class="left-sidebar-body">
	<h1><?=$collection->name?></h1>
	<hr>
	<div class="models">
		<div id="image" class="image fl">
			<em>&nbsp;</em>
			<a rel="prettyPhoto" href="/<?=$mainModelPhotoPath . '/' . $mainModelPhoto->getFilename()?>"><img src="/<?=$mainModelPhotoUrl?>" alt="<?=$model->name?>"></a>
		</div>
		<?php if (count($photos) > 0) { ?>
		<div id="thumbnailsContainer"><ul id="thumbnails" class="fl">
			<?php foreach($photos as /** @var Model_ModelPhoto $photo */$photo) { ?><li>
				<div class="profile-image small">
					<em>&nbsp;</em>
					<a href="/<?=$mainModelPhotoPath . '/' . $photo->getFilename()?>" data-src="/<?=$mainModelPhotoPath . '/' . $photo->getFilename(Model_ModelPhoto::SIZE_BIG)?>">
						<img src="/<?=$mainModelPhotoPath . '/' . $photo->getFilename(Model_ModelPhoto::SIZE_SMALL)?>" alt="<?=$model->name?>">
					</a>
				</div>
			</li><?php } ?>
		</ul></div>
		<?php } ?>
		<h2><?=$model->name?></h2>
		<p><?=$model->description?></p>
	</div>
	<div id="model-nav">
		<ul>
			<?php if (!$prev->isEmpty()) { ?>
			<li class="prev"><a href="<?=$this->url(array(
								'model_id' => $prev->id,
								'model_name_hash' => $this->urlPartTranslit($prev->name)
						   ), 'model', true)?>">&lt;&lt;&nbsp;<?=$this->translate('Предыдущая модель')?></a></li>
			<?php } ?>
			<?php if (!$next->isEmpty()) { ?>
			<li class="next"><a href="<?=$this->url(array(
								'model_id' => $next->id,
								'model_name_hash' => $this->urlPartTranslit($next->name)
						   ), 'model', true)?>"><?=$this->translate('Следующая модель')?>&nbsp;&gt;&gt;</a></li>
			<?php } ?>
		</ul>
		<p><a href="<?=$this->url(array(
		                                'collection_id' => $collection->id,
			                            'collection_name_hash' => $this->urlPartTranslit($collection->name)
		                           ), 'collectionModelsChain', true)?>">&lt;&lt;&nbsp;<?=$this->translate('Назад к коллекции')?></a></p>
	</div>
</div>
<?php
	$this->headScript()
		->appendFile('/js/jscrollpane/jquery.mousewheel.js')
		->appendFile('/js/jscrollpane/jquery.jscrollpane.min.js')
		->appendFile('/js/prettyPhoto/jquery.prettyPhoto.js')
		->appendFile('/js/model.js');

	$this->headLink()
		->appendStylesheet('/css/jquery.jscrollpane.css')
		->appendStylesheet('/css/prettyPhoto.css');

	$this->headTitle($this->translate('Коллекция') . ' «' . $model->getCollection()->name . '» - «' . $model->name . '»');
?>