<div id="sidebar" class="shape">
	<h1>Наши коллекции</h1>
	<ul>
		<li><a href="#ketty">Ketty Perry</a></li>
		<li><a href="#trololo">Ololo Trololo</a></li>
		<li class="active"><a href="#helen">Helen Banks</a></li>
		<li><a href="#babka">Babka Paraska</a></li>
		<li><a href="#roland">Roland Emmelrich</a></li>
		<li><a href="#kelvin">Kelvin Klein</a></li>
	</ul>
</div>
<div id="model" class="left-sidebar-body">
	<h1>Babka Paraska Model New</h1>
	<hr>
	<div class="models">
		<div class="image fl"><em>&nbsp;</em><img src="/images/crap/collection_model_1.jpg" alt="Платье Кармэн"></div>
		<ul id="thumbnails" class="fl">
			<li>
				<div class="profile-image small">
					<em>&nbsp;</em>
					<a href="#model1">
						<img src="/images/crap/image8.jpg" alt="Платье Кармэн">
					</a>
				</div>
			</li>
			<li>
				<div class="profile-image small">
					<em>&nbsp;</em>
					<a href="#model1">
						<img src="/images/crap/image8.jpg" alt="Платье Кармэн">
					</a>
				</div>
			</li>
			<li>
				<div class="profile-image small">
					<em>&nbsp;</em>
					<a href="#model1">
						<img src="/images/crap/image8.jpg" alt="Платье Кармэн">
					</a>
				</div>
			</li>
		</ul>
		<h2>Платье Кармэн</h2>
		<p>В одном из романтичных переулков Остоженки рядом с Храмом Христа Спасителя и Пречистенской набережной находится салон свадебного платья с интригующим и вкусным названием "Ваниль". В коллекции свадебного салона большой выбор самых модных иэксклюзивных свадебных платьев напрокат.</p>
	</div>
	<div id="model-nav">
		<ul>
			<li class="prev"><a href="#prev">&lt;&lt;&nbsp;Предыдущая модель</a></li>
			<li class="next"><a href="#next">Следующая модель&nbsp;&gt;&gt;</a></li>
		</ul>
		<p><a href="#back">&lt;&lt;&nbsp;Назад к коллекции</a></p>
	</div>
</div>